@startuml
start
:Пользователь открывает канбан-доску;
if (Пользователь хочет создать задачу?) then (да)
  :Пользователь создает новую задачу;
elseif (Пользователь хочет просмотреть задачи?) then (да)
  :Пользователь просматривает список задач;
elseif (Пользователь хочет редактировать задачу?) then (да)
  :Пользователь редактирует задачу;
elseif (Пользователь хочет удалить задачу?) then (да)
  :Пользователь удаляет задачу;
elseif (Пользователь хочет переместить задачу?) then (да)
  :Пользователь перемещает задачу между колонками;
elseif (Происходит автоматическое обновление?) then (да)
  :Доска автоматически обновляется;
else (нет)
  :Действие пользователя не определено;
endif
stop
@enduml
